package registro.eingv.uabc.registroeingv.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig registroDaoConfig;

    private final RegistroDao registroDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        registroDaoConfig = daoConfigMap.get(RegistroDao.class).clone();
        registroDaoConfig.initIdentityScope(type);

        registroDao = new RegistroDao(registroDaoConfig, this);

        registerDao(Registro.class, registroDao);
    }
    
    public void clear() {
        registroDaoConfig.getIdentityScope().clear();
    }

    public RegistroDao getRegistroDao() {
        return registroDao;
    }

}
