package registro.eingv.uabc.registroeingv.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table REGISTRO.
*/
public class RegistroDao extends AbstractDao<Registro, Long> {

    public static final String TABLENAME = "REGISTRO";

    /**
     * Properties of entity Registro.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_ID");
        public final static Property Latitud = new Property(1, Float.class, "latitud", false, "LATITUD");
        public final static Property Longitud = new Property(2, Float.class, "longitud", false, "LONGITUD");
        public final static Property Altitud = new Property(3, Float.class, "altitud", false, "ALTITUD");
        public final static Property Lugar = new Property(4, String.class, "lugar", false, "LUGAR");
    };


    public RegistroDao(DaoConfig config) {
        super(config);
    }
    
    public RegistroDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'REGISTRO' (" + //
                "'_ID' INTEGER PRIMARY KEY ," + // 0: _id
                "'LATITUD' REAL," + // 1: latitud
                "'LONGITUD' REAL," + // 2: longitud
                "'ALTITUD' REAL," + // 3: altitud
                "'LUGAR' TEXT);"); // 4: lugar
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'REGISTRO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Registro entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        Float latitud = entity.getLatitud();
        if (latitud != null) {
            stmt.bindDouble(2, latitud);
        }
 
        Float longitud = entity.getLongitud();
        if (longitud != null) {
            stmt.bindDouble(3, longitud);
        }
 
        Float altitud = entity.getAltitud();
        if (altitud != null) {
            stmt.bindDouble(4, altitud);
        }
 
        String lugar = entity.getLugar();
        if (lugar != null) {
            stmt.bindString(5, lugar);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Registro readEntity(Cursor cursor, int offset) {
        Registro entity = new Registro( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getFloat(offset + 1), // latitud
            cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2), // longitud
            cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3), // altitud
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // lugar
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Registro entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLatitud(cursor.isNull(offset + 1) ? null : cursor.getFloat(offset + 1));
        entity.setLongitud(cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2));
        entity.setAltitud(cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3));
        entity.setLugar(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Registro entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Registro entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
