package registro.eingv.uabc.registroeingv.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table REGISTRO.
 */
public class Registro implements Serializable{

    private Long _id;
    private Float latitud;
    private Float longitud;
    private String descripcion;
    private String lugar;

    public Registro() {
    }

    public Registro(Long _id) {
        this._id = _id;
    }

    public Registro(Long _id, Float latitud, Float longitud, String descripcion, String lugar) {
        this._id = _id;
        this.latitud = latitud;
        this.longitud = longitud;
        this.descripcion = descripcion;
        this.lugar = lugar;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public Float getLatitud() {
        return latitud;
    }

    public void setLatitud(Float latitud) {
        this.latitud = latitud;
    }

    public Float getLongitud() {
        return longitud;
    }

    public void setLongitud(Float longitud) {
        this.longitud = longitud;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getLugar() {
        return lugar;
    }

    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

}
